/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ucocampusmaps;

import java.awt.Font;
import java.util.Locale;
import java.util.ResourceBundle;
import static ucocampusmaps.Portada.bundle;
import static ucocampusmaps.Portada.flag;

/**
 *
 * @author jesem
 */
public class CitaSecretaria extends javax.swing.JFrame {
    public Portada padre;
    /**
     * Creates new form CitaSecretaria
     */
    public CitaSecretaria() {
        initComponents();
        this.setLocationRelativeTo(null);
        NumeroPedido.setFont(new Font("Serif", Font.PLAIN, 32));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Politecnica = new javax.swing.JButton();
        Ciencias = new javax.swing.JButton();
        Veterinaria = new javax.swing.JButton();
        Turismo = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        NumeroPedido = new javax.swing.JLabel();
        FondoNumero = new javax.swing.JLabel();
        BackGround = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        Politecnica.setText("Politecnica");
        Politecnica.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PolitecnicaMouseClicked(evt);
            }
        });
        jPanel1.add(Politecnica);
        Politecnica.setBounds(100, 110, 140, 40);

        Ciencias.setText("Ciencias");
        Ciencias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CienciasMouseClicked(evt);
            }
        });
        jPanel1.add(Ciencias);
        Ciencias.setBounds(100, 190, 140, 40);

        Veterinaria.setText("Veterinaria");
        Veterinaria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VeterinariaMouseClicked(evt);
            }
        });
        jPanel1.add(Veterinaria);
        Veterinaria.setBounds(100, 350, 140, 40);

        Turismo.setText("Turismo");
        Turismo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TurismoMouseClicked(evt);
            }
        });
        jPanel1.add(Turismo);
        Turismo.setBounds(100, 270, 140, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/flecha.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel2);
        jLabel2.setBounds(120, 500, 100, 70);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/esp.jpg"))); // NOI18N
        jPanel1.add(jLabel4);
        jLabel4.setBounds(270, 10, 70, 60);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pedir_cita.jpg"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(-6, -6, 260, 50);
        jPanel1.add(NumeroPedido);
        NumeroPedido.setBounds(120, 460, 80, 40);

        FondoNumero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/banda_numero.jpg"))); // NOI18N
        FondoNumero.setText("b");
        jPanel1.add(FondoNumero);
        FondoNumero.setBounds(0, 450, 340, 50);

        BackGround.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/background.png"))); // NOI18N
        jPanel1.add(BackGround);
        BackGround.setBounds(0, 0, 340, 590);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 343, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 587, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        padre.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void PolitecnicaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PolitecnicaMouseClicked
        // TODO add your handling code here:
        SecretariaNumero.facultad="Politecnica";
        //adre.setVisible(true);
        //this.setVisible(false);
        NumeroPedido.setText("P242");
    }//GEN-LAST:event_PolitecnicaMouseClicked

    private void CienciasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CienciasMouseClicked
        // TODO add your handling code here:
        SecretariaNumero.facultad="Ciencias";
       // padre.setVisible(true);
        //this.setVisible(false);
        NumeroPedido.setText("C242");
    }//GEN-LAST:event_CienciasMouseClicked

    private void VeterinariaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VeterinariaMouseClicked
        // TODO add your handling code here:
        SecretariaNumero.facultad="Veterinaria";
       // padre.setVisible(true);
        //this.setVisible(false);
        NumeroPedido.setText("V242");
    }//GEN-LAST:event_VeterinariaMouseClicked

    private void TurismoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TurismoMouseClicked
        // TODO add your handling code here:
        SecretariaNumero.facultad="Turismo";
        //padre.setVisible(true);
        //this.setVisible(false);
        NumeroPedido.setText("T242");
    }//GEN-LAST:event_TurismoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CitaSecretaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CitaSecretaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CitaSecretaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CitaSecretaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CitaSecretaria().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BackGround;
    private javax.swing.JButton Ciencias;
    private javax.swing.JLabel FondoNumero;
    private javax.swing.JLabel NumeroPedido;
    private javax.swing.JButton Politecnica;
    private javax.swing.JButton Turismo;
    private javax.swing.JButton Veterinaria;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    

}
