/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ucocampusmaps;

import javax.swing.ImageIcon;

/**
 *
 * @author jesem
 */
public class mapaUco extends javax.swing.JFrame {
    public Portada padre;
    //public Portada ventanaPortada=new Portada();
    /**
     * Creates new form mapaUco
     */
    public mapaUco() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        CharlesDarwin = new javax.swing.JLabel();
        GregorMendel = new javax.swing.JLabel();
        JoseCelestinoMutis = new javax.swing.JLabel();
        AlbertEinstein = new javax.swing.JLabel();
        MarieCurie = new javax.swing.JLabel();
        SanidadAnimal = new javax.swing.JLabel();
        SeveroOchoa = new javax.swing.JLabel();
        AularioAverroes = new javax.swing.JLabel();
        HospitalVeterinario = new javax.swing.JLabel();
        LeonardoDaVinci = new javax.swing.JLabel();
        RamonYCajal = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        FotoMaps = new javax.swing.JLabel();
        Show = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/esp.jpg"))); // NOI18N
        jPanel1.add(jLabel4);
        jLabel4.setBounds(270, 0, 70, 60);
        jPanel1.add(CharlesDarwin);
        CharlesDarwin.setBounds(160, 180, 50, 50);
        jPanel1.add(GregorMendel);
        GregorMendel.setBounds(200, 280, 50, 50);
        jPanel1.add(JoseCelestinoMutis);
        JoseCelestinoMutis.setBounds(230, 270, 50, 50);
        jPanel1.add(AlbertEinstein);
        AlbertEinstein.setBounds(200, 170, 50, 50);
        jPanel1.add(MarieCurie);
        MarieCurie.setBounds(230, 180, 50, 50);
        jPanel1.add(SanidadAnimal);
        SanidadAnimal.setBounds(120, 80, 50, 50);
        jPanel1.add(SeveroOchoa);
        SeveroOchoa.setBounds(170, 270, 50, 50);
        jPanel1.add(AularioAverroes);
        AularioAverroes.setBounds(110, 280, 50, 50);
        jPanel1.add(HospitalVeterinario);
        HospitalVeterinario.setBounds(160, 100, 50, 50);
        jPanel1.add(LeonardoDaVinci);
        LeonardoDaVinci.setBounds(30, 190, 50, 50);
        jPanel1.add(RamonYCajal);
        RamonYCajal.setBounds(130, 140, 50, 50);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/mapa_interactivo.jpg"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(0, 0, 250, 60);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Alber Einstein", "Aulario Averroes", "José Celestino Mutis", "Charles Darwin", "Grego Mendel", "HOspital Veterinario E Santisteban", "Marie Curie", "Ramón y Cajal", "Sanidad Animal", "Severo Ochoa", "Leonardo Da Vinci" }));
        jPanel1.add(jComboBox2);
        jComboBox2.setBounds(20, 420, 280, 20);

        FotoMaps.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/campus.jpg"))); // NOI18N
        jPanel1.add(FotoMaps);
        FotoMaps.setBounds(0, 80, 350, 320);

        Show.setText("Mostrar");
        Show.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ShowMouseClicked(evt);
            }
        });
        jPanel1.add(Show);
        Show.setBounds(140, 560, 200, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/flecha.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 560, 100, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/background.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 350, 610);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 609, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ShowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ShowMouseClicked
        // TODO add your handling code here:
        
        String lugarMostrar=jComboBox2.getSelectedItem().toString();
        
        if("Alber Einstein".equals(lugarMostrar))
        {
            AlbertEinstein.setIcon(new ImageIcon(getClass().getResource("/images/circulo.png")));
        }
        else
        {
            AlbertEinstein.setIcon(null);
        }
        if("Aulario Averroes".equals(lugarMostrar))
        {
             AularioAverroes.setIcon(new ImageIcon(getClass().getResource("/images/circulo.png")));
        }
        else
        {
            AularioAverroes.setIcon(null);
        }
        if("José Celestino Mutis".equals(lugarMostrar))
        {
            JoseCelestinoMutis.setIcon(new ImageIcon(getClass().getResource("/images/circulo.png")));
        }
        else
        {
            JoseCelestinoMutis.setIcon(null);
        }
        if("Charles Darwin".equals(lugarMostrar))
        {
            CharlesDarwin.setIcon(new ImageIcon(getClass().getResource("/images/circulo.png")));
        }
        else
        {
            CharlesDarwin.setIcon(null);
        }
        if("Grego Mendel".equals(lugarMostrar))
        {
            GregorMendel.setIcon(new ImageIcon(getClass().getResource("/images/circulo.png")));
        }
        else
        {
            GregorMendel.setIcon(null);
        }
        if("HOspital Veterinario E Santisteban".equals(lugarMostrar))
        {
            HospitalVeterinario.setIcon(new ImageIcon(getClass().getResource("/images/circulo.png")));
        }
        else
        {
            HospitalVeterinario.setIcon(null);
        }
        if("Marie Curie".equals(lugarMostrar))
        {
            MarieCurie.setIcon(new ImageIcon(getClass().getResource("/images/circulo.png")));
        }
        else
        {
            MarieCurie.setIcon(null);
        }
        if("Ramón y Cajal".equals(lugarMostrar))
        {
            RamonYCajal.setIcon(new ImageIcon(getClass().getResource("/images/circulo.png")));
        }
        else
        {
            RamonYCajal.setIcon(null);
        }
        if("Sanidad Animal".equals(lugarMostrar))
        {
            SanidadAnimal.setIcon(new ImageIcon(getClass().getResource("/images/circulo.png")));
        }
        else
        {
            SanidadAnimal.setIcon(null);
        }
        if("Severo Ochoa".equals(lugarMostrar))
        {
            SeveroOchoa.setIcon(new ImageIcon(getClass().getResource("/images/circulo.png")));
        }
        else
        {
            SeveroOchoa.setIcon(null);
        }
        if("Leonardo Da Vinci".equals(lugarMostrar))
        {
            LeonardoDaVinci.setIcon(new ImageIcon(getClass().getResource("/images/circulo.png")));
        }
        else
        {
            LeonardoDaVinci.setIcon(null);
        }
    }//GEN-LAST:event_ShowMouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:this.setVisible(false);
       this.setVisible(false);
        padre.setVisible(true);
    }//GEN-LAST:event_jLabel2MouseClicked

    /**
     * @param args the command line arguments
     */

    
    
    
    

    
  
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AlbertEinstein;
    private javax.swing.JLabel AularioAverroes;
    private javax.swing.JLabel CharlesDarwin;
    private javax.swing.JLabel FotoMaps;
    private javax.swing.JLabel GregorMendel;
    private javax.swing.JLabel HospitalVeterinario;
    private javax.swing.JLabel JoseCelestinoMutis;
    private javax.swing.JLabel LeonardoDaVinci;
    private javax.swing.JLabel MarieCurie;
    private javax.swing.JLabel RamonYCajal;
    private javax.swing.JLabel SanidadAnimal;
    private javax.swing.JLabel SeveroOchoa;
    private javax.swing.JButton Show;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
