/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ucocampusmaps;

import java.util.Locale;
import java.util.ResourceBundle;
import javax.swing.Icon;

/**
 *
 * @author jesem
 */
public class Portada extends javax.swing.JFrame {

    /**
     * Creates new form Portada
     */
    
    public static Locale locale;
    public static ResourceBundle bundle;
    public mapaUco ventanaMapaUco=new mapaUco();
    public CitaSecretaria secretaria = new CitaSecretaria();
    public SecretariaNumero secretariaNumero = new SecretariaNumero();
    public Portada() {
        initComponents();   
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ShowRequest = new javax.swing.JButton();
        Icon = new javax.swing.JLabel();
        Map = new javax.swing.JButton();
        AskRequest = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("ucocampusmaps/Bundle"); // NOI18N
        ShowRequest.setText(bundle.getString("Portada.ShowRequest.text")); // NOI18N
        ShowRequest.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ShowRequestMouseClicked(evt);
            }
        });
        jPanel1.add(ShowRequest);
        ShowRequest.setBounds(40, 440, 250, 40);

        Icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Logounicordoba.svg.png"))); // NOI18N
        jPanel1.add(Icon);
        Icon.setBounds(90, 80, 150, 127);

        Map.setText(bundle.getString("Portada.Map.text")); // NOI18N
        Map.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MapMouseClicked(evt);
            }
        });
        Map.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MapActionPerformed(evt);
            }
        });
        jPanel1.add(Map);
        Map.setBounds(40, 280, 250, 40);

        AskRequest.setText(bundle.getString("Portada.AskRequest.text")); // NOI18N
        AskRequest.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AskRequestMouseClicked(evt);
            }
        });
        jPanel1.add(AskRequest);
        AskRequest.setBounds(40, 360, 250, 40);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/esp.jpg"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel3);
        jLabel3.setBounds(270, 0, 70, 60);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cuadro_dialogoMP.jpg"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(-6, -6, 160, 50);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/background.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(-16, -6, 370, 600);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 344, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 584, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void AskRequestMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AskRequestMouseClicked
        // TODO add your handling code here:
        secretaria.setVisible(true);
        secretaria.padre=this;
        this.setVisible(false);
        
        
    }//GEN-LAST:event_AskRequestMouseClicked

    private void MapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MapMouseClicked
        ventanaMapaUco.setVisible(true);
        ventanaMapaUco.padre=this;
        this.setVisible(false);
    }//GEN-LAST:event_MapMouseClicked

    private void ShowRequestMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ShowRequestMouseClicked
        // TODO add your handling code here:
        if(SecretariaNumero.facultad!="null")
        {
            secretariaNumero.setVisible(true);
        secretariaNumero.padre=this;
        this.setVisible(false);
        }
    }//GEN-LAST:event_ShowRequestMouseClicked

    private void MapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MapActionPerformed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        if(flag==0)
        {
            locale = new Locale("en", "GB");
            bundle= ResourceBundle.getBundle("ucocampusmaps/Bundle_en_GB",locale);
            cambiarIdioma();
            jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/eng.jpg")));
            flag=1;
        }
        else
        {
            locale = new Locale("es", "ES");
            bundle= ResourceBundle.getBundle("ucocampusmaps/Bundle",locale);
            cambiarIdioma();
            jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/esp.jpg")));
            flag=0;
        }
    }//GEN-LAST:event_jLabel3MouseClicked

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Portada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Portada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Portada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Portada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Portada().setVisible(true);
                
            }
        });
    }

    //0 -> ESP
    //1 -> ENG
    public static int flag=0;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AskRequest;
    private javax.swing.JLabel Icon;
    private javax.swing.JButton Map;
    private javax.swing.JButton ShowRequest;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    private void cambiarIdioma() {

        Map.setText(bundle.getString("Portada.Map.text"));
        AskRequest.setText(bundle.getString("Portada.AskRequest.text"));
        ShowRequest.setText(bundle.getString("Portada.AskRequest.text"));
    }
}
