/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ucocampusmaps;

import java.awt.Font;

/**
 *
 * @author jesem
 */
public class SecretariaNumero extends javax.swing.JFrame {
    /**
     * Creates new form SecretariaNumero
     */
    

    
    public Portada padre;
    public static String facultad="null";
    
    public SecretariaNumero() {
        initComponents();  
        this.setLocationRelativeTo(null);
        TuNumero.setFont(new Font("Serif", Font.PLAIN, 32));
        
    }

    public void Start()
    {

        if("Politecnica".equals(facultad))
             TuNumero.setText("P242");
        if("Ciencias".equals(facultad))
            TuNumero.setText("C242");
        if("Veterinaria".equals(facultad))
            TuNumero.setText("V242");
        if("Turismo".equals(facultad))
            TuNumero.setText("T242");

        
        FondoNumero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/banda_numero.jpg"))); // NOI18N
        FondoSecretaria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/showCita.png"))); // NOI18N
    }
       
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BotonAtras = new javax.swing.JLabel();
        MostrarCita = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        TuNumero = new javax.swing.JLabel();
        FondoNumero = new javax.swing.JLabel();
        FondoSecretaria = new javax.swing.JLabel();
        BackGround = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        BotonAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/flecha.png"))); // NOI18N
        BotonAtras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonAtrasMouseClicked(evt);
            }
        });
        jPanel1.add(BotonAtras);
        BotonAtras.setBounds(250, 0, 140, 50);

        MostrarCita.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/mostrar_cita.jpg"))); // NOI18N
        jPanel1.add(MostrarCita);
        MostrarCita.setBounds(0, 0, 250, 50);

        jButton1.setText("Mostrar Cita");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(80, 250, 190, 50);
        jPanel1.add(TuNumero);
        TuNumero.setBounds(110, 540, 100, 50);
        jPanel1.add(FondoNumero);
        FondoNumero.setBounds(0, 540, 340, 50);
        jPanel1.add(FondoSecretaria);
        FondoSecretaria.setBounds(0, 70, 350, 470);

        BackGround.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/background.png"))); // NOI18N
        jPanel1.add(BackGround);
        BackGround.setBounds(0, 0, 340, 590);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 346, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 592, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        jButton1.setVisible(false);
        Start();

    }//GEN-LAST:event_jButton1MouseClicked

    private void BotonAtrasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonAtrasMouseClicked
        // TODO add your handling code here:
        
        
        FondoSecretaria.setIcon(null); 
        TuNumero.setText(null);
        FondoNumero.setIcon(null);
        padre.setVisible(true);
        initComponents();
        TuNumero.setFont(new Font("Serif", Font.PLAIN, 32));
        this.setVisible(false);
    }//GEN-LAST:event_BotonAtrasMouseClicked

       
            
        
    /**
     * @param args the command line arguments
     */
    public void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SecretariaNumero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SecretariaNumero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SecretariaNumero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SecretariaNumero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new SecretariaNumero().setVisible(true);
                
            }
        });
        
     
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BackGround;
    private javax.swing.JLabel BotonAtras;
    private javax.swing.JLabel FondoNumero;
    private javax.swing.JLabel FondoSecretaria;
    private javax.swing.JLabel MostrarCita;
    private javax.swing.JLabel TuNumero;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
    
    
    
}
