/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ucocampusmaps;

/**
 *
 * @author jesem
 */
public class SecretariaNumero extends javax.swing.JFrame {

    /**
     * Creates new form SecretariaNumero
     */
    

    
    public Portada padre;
    public static String facultad="null";
    
    public SecretariaNumero() {
        initComponents();  
        
    }

    public void Start()
    {
        
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/1.png"))); // NOI18N
        jPanel1.add(jLabel4);
        jLabel4.setBounds(360, 210, 170, 150);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/1.png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(610, 220, 170, 150);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/5.png"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(880, 220, 170, 150);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/1.png"))); // NOI18N
        jPanel1.add(jLabel5);
        jLabel5.setBounds(360, 0, 170, 150);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/4.png"))); // NOI18N
        jPanel1.add(jLabel6);
        jLabel6.setBounds(590, 0, 170, 150);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/1.png"))); // NOI18N
        jPanel1.add(jLabel7);
        jLabel7.setBounds(870, 0, 170, 150);
        jPanel1.add(LetraTuya);
        LetraTuya.setBounds(130, 10, 190, 140);

        jLabel9.setText("NUMERO ACTUAL");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(20, 300, 110, 50);

        jLabel10.setText("TU NUMERO");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(30, 110, 90, 14);
        
        
        if ("Politecnica".equals(facultad))
         {
             LetraTuya.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/P.png")));
             LetraActual.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/P.png")));
         }
         if ("Ciencias".equals(facultad))
         {
             LetraTuya.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/C.png")));
             LetraActual.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/C.png")));
         }

         if ("Turismo".equals(facultad))
         {
             LetraTuya.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/T.png")));
             LetraActual.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/T.png")));
         }

         if ("Veterinaria".equals(facultad))
         {
             LetraTuya.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/V.png")));
             LetraActual.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/V.png")));
         }
    }
    
    
    public void Finish()
    {
         jLabel4.setIcon(null); // NOI18N
        jPanel1.add(jLabel4);
        jLabel4.setBounds(360, 210, 170, 150);

        jLabel2.setIcon(null); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(610, 220, 170, 150);

        jLabel3.setIcon(null); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(880, 220, 170, 150);

        jLabel5.setIcon(null); // NOI18N
        jPanel1.add(jLabel5);
        jLabel5.setBounds(360, 0, 170, 150);

        jLabel6.setIcon(null); // NOI18N
        jPanel1.add(jLabel6);
        jLabel6.setBounds(590, 0, 170, 150);

        jLabel7.setIcon(null); // NOI18N
        jPanel1.add(jLabel7);
        jLabel7.setBounds(870, 0, 170, 150);
        jPanel1.add(LetraTuya);
        LetraTuya.setBounds(130, 10, 190, 140);

        jLabel9.setText("");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(20, 300, 110, 50);

        jLabel10.setText("");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(30, 110, 90, 14);
        
        
       
        LetraTuya.setIcon(null);
        LetraActual.setIcon(null);
         this.ShowCita.setVisible(false);
         
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LetraActual = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        LetraTuya = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        ShowCita = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);
        jPanel1.add(LetraActual);
        LetraActual.setBounds(130, 220, 190, 140);
        jPanel1.add(jLabel4);
        jLabel4.setBounds(360, 210, 170, 150);
        jPanel1.add(jLabel2);
        jLabel2.setBounds(610, 220, 170, 150);
        jPanel1.add(jLabel3);
        jLabel3.setBounds(880, 220, 170, 150);
        jPanel1.add(jLabel5);
        jLabel5.setBounds(360, 0, 170, 150);
        jPanel1.add(jLabel6);
        jLabel6.setBounds(590, 0, 170, 150);
        jPanel1.add(jLabel7);
        jLabel7.setBounds(870, 0, 170, 150);
        jPanel1.add(LetraTuya);
        LetraTuya.setBounds(130, 10, 190, 140);
        jPanel1.add(jLabel9);
        jLabel9.setBounds(20, 300, 110, 50);
        jPanel1.add(jLabel10);
        jLabel10.setBounds(30, 110, 90, 0);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/flecha.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 10, 120, 70);

        ShowCita.setText("Mostrar Cita");
        ShowCita.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ShowCitaMouseClicked(evt);
            }
        });
        jPanel1.add(ShowCita);
        ShowCita.setBounds(440, 140, 250, 80);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1051, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        
        
        padre.setVisible(true);
        this.setVisible(false);
        Finish();
        this.initComponents();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void ShowCitaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ShowCitaMouseClicked
        // TODO add your handling code here:
        this.ShowCita.setVisible(false);
       
        
        Start();
    }//GEN-LAST:event_ShowCitaMouseClicked

       
            
        
    /**
     * @param args the command line arguments
     */
    public void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SecretariaNumero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SecretariaNumero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SecretariaNumero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SecretariaNumero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new SecretariaNumero().setVisible(true);
                
            }
        });
        
     
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LetraActual;
    private javax.swing.JLabel LetraTuya;
    private javax.swing.JButton ShowCita;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
