/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package radio;

import java.awt.Color;
import java.awt.Image;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseMotionAdapter;
import java.io.IOException;
import javax.sound.sampled.*;
import javax.swing.ImageIcon;
import sun.applet.Main;

/**
 *
 * @author jesus
 */
public class Radio extends javax.swing.JFrame {

    int ch = 0;
    int th = 0;
    int chan1, chan2, chan3, chan4;
    boolean on = false;
    int x_pressed;
    int y_pressed;
    
    MouseAdapter Madapter = new MouseAdapter(){
        @Override
        public void mousePressed(MouseEvent e) {
            //catching the current values for x,y coordinates on screen
            x_pressed = e.getX();
            y_pressed = e.getY();
        }
    };

    MouseMotionAdapter MMadapter1 = new MouseMotionAdapter(){
        @Override
        public void mouseDragged(MouseEvent e){
            //and when the Jlabel is dragged
            icon1.setLocation(e.getXOnScreen() - x_pressed - 430, e.getYOnScreen() - y_pressed - 272);
            del1.setLocation(e.getXOnScreen() - x_pressed - 430, e.getYOnScreen() - y_pressed - 272);
            text1.setLocation(e.getXOnScreen() - x_pressed - 430, e.getYOnScreen() - y_pressed - 272);
        }
    };
    MouseMotionAdapter MMadapter2 = new MouseMotionAdapter(){
        @Override
        public void mouseDragged(MouseEvent e){
            //and when the Jlabel is dragged
            icon2.setLocation(e.getXOnScreen() - x_pressed - 430, e.getYOnScreen() - y_pressed - 272);
            del2.setLocation(e.getXOnScreen() - x_pressed - 430, e.getYOnScreen() - y_pressed - 272);
            text2.setLocation(e.getXOnScreen() - x_pressed - 430, e.getYOnScreen() - y_pressed - 272);
        }
    };
    MouseMotionAdapter MMadapter3 = new MouseMotionAdapter(){
        @Override
        public void mouseDragged(MouseEvent e){
            //and when the Jlabel is dragged
            icon3.setLocation(e.getXOnScreen() - x_pressed - 430, e.getYOnScreen() - y_pressed - 272);
            del3.setLocation(e.getXOnScreen() - x_pressed - 430, e.getYOnScreen() - y_pressed - 272);
            text3.setLocation(e.getXOnScreen() - x_pressed - 430, e.getYOnScreen() - y_pressed - 272);
        }
    };
    MouseMotionAdapter MMadapter4 = new MouseMotionAdapter(){
        @Override
        public void mouseDragged(MouseEvent e){
            //and when the Jlabel is dragged
            icon4.setLocation(e.getXOnScreen() - x_pressed - 430, e.getYOnScreen() - y_pressed - 272);
            del4.setLocation(e.getXOnScreen() - x_pressed - 430, e.getYOnScreen() - y_pressed - 272);
            text4.setLocation(e.getXOnScreen() - x_pressed - 430, e.getYOnScreen() - y_pressed - 272);
        }
    };
    
    /**
     * Creates new form Radio
     */
    public Radio() {
        initComponents();
        
        setLocationRelativeTo(null);
        
        icon1.addMouseListener(Madapter);
        icon2.addMouseListener(Madapter);
        icon3.addMouseListener(Madapter);
        icon4.addMouseListener(Madapter);
        icon1.addMouseMotionListener(MMadapter1);
        icon2.addMouseMotionListener(MMadapter2);
        icon3.addMouseMotionListener(MMadapter3);
        icon4.addMouseMotionListener(MMadapter4);
        icon1.setVisible(false);
        icon2.setVisible(false);
        icon3.setVisible(false);
        icon4.setVisible(false);
        text1.setVisible(false);
        text2.setVisible(false);
        text3.setVisible(false);
        text4.setVisible(false);
        del1.setVisible(false);
        del2.setVisible(false);
        del3.setVisible(false);
        del4.setVisible(false);
        this.setIconImage(new ImageIcon(getClass().getResource("/img/music.png")).getImage());
        this.setTitle("Radio SI 2016");
        //this.setUndecorated(true);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jSlider1 = new javax.swing.JSlider();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        del1 = new javax.swing.JButton();
        text1 = new javax.swing.JLabel();
        icon1 = new javax.swing.JLabel();
        del2 = new javax.swing.JButton();
        text2 = new javax.swing.JLabel();
        icon2 = new javax.swing.JLabel();
        del3 = new javax.swing.JButton();
        text3 = new javax.swing.JLabel();
        icon3 = new javax.swing.JLabel();
        del4 = new javax.swing.JButton();
        text4 = new javax.swing.JLabel();
        icon4 = new javax.swing.JLabel();
        BG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(560, 320));
        setMinimumSize(new java.awt.Dimension(560, 320));
        setPreferredSize(new java.awt.Dimension(560, 320));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 100, 245));
        jPanel1.setAutoscrolls(true);
        jPanel1.setMaximumSize(new java.awt.Dimension(560, 320));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(175, 175, 250));
        jPanel2.setLayout(null);

        jButton1.setBackground(new java.awt.Color(235, 235, 250));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/prev.png"))); // NOI18N
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(0, 0, 44, 101);

        jButton2.setBackground(new java.awt.Color(235, 235, 250));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/next.png"))); // NOI18N
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jPanel2.add(jButton2);
        jButton2.setBounds(492, 0, 44, 101);

        jButton3.setBackground(new java.awt.Color(210, 210, 2));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/star.png"))); // NOI18N
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jPanel2.add(jButton3);
        jButton3.setBounds(230, 60, 80, 40);

        jLabel3.setBackground(new java.awt.Color(20, 20, 60));
        jLabel3.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(20, 20, 60));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("OFF");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(170, 10, 199, 46);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(12, 12, 536, 100);

        jSlider1.setBackground(new java.awt.Color(235, 235, 250));
        jPanel1.add(jSlider1);
        jSlider1.setBounds(50, 130, 458, 54);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/volumen_menos.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(60, 120, 27, 27);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/volumen_mas.png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(470, 120, 27, 27);

        jButton8.setBackground(new java.awt.Color(235, 235, 250));
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/on.png"))); // NOI18N
        jButton8.setToolTipText("");
        jButton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton8MouseClicked(evt);
            }
        });
        jPanel1.add(jButton8);
        jButton8.setBounds(20, 240, 44, 44);

        jButton9.setBackground(new java.awt.Color(15, 245, 15));
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/palet.png"))); // NOI18N
        jButton9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton9MouseClicked(evt);
            }
        });
        jPanel1.add(jButton9);
        jButton9.setBounds(20, 180, 44, 44);

        del1.setBackground(new java.awt.Color(235, 15, 15));
        del1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/x.png"))); // NOI18N
        del1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                del1MouseClicked(evt);
            }
        });
        jPanel1.add(del1);
        del1.setBounds(150, 230, 20, 20);

        text1.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        text1.setForeground(new java.awt.Color(235, 235, 250));
        text1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        text1.setToolTipText("");
        text1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(text1);
        text1.setBounds(150, 230, 80, 20);

        icon1.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        icon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/music.png"))); // NOI18N
        icon1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                icon1MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                icon1MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                icon1MouseEntered(evt);
            }
        });
        jPanel1.add(icon1);
        icon1.setBounds(150, 230, 50, 51);

        del2.setBackground(new java.awt.Color(235, 15, 15));
        del2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/x.png"))); // NOI18N
        del2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                del2MouseClicked(evt);
            }
        });
        jPanel1.add(del2);
        del2.setBounds(220, 230, 20, 20);

        text2.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        text2.setForeground(new java.awt.Color(235, 235, 250));
        text2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        text2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(text2);
        text2.setBounds(220, 230, 80, 20);

        icon2.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        icon2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/music.png"))); // NOI18N
        icon2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                icon2MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                icon2MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                icon2MouseEntered(evt);
            }
        });
        jPanel1.add(icon2);
        icon2.setBounds(220, 230, 50, 51);

        del3.setBackground(new java.awt.Color(235, 15, 15));
        del3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/x.png"))); // NOI18N
        del3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                del3MouseClicked(evt);
            }
        });
        jPanel1.add(del3);
        del3.setBounds(290, 230, 20, 20);

        text3.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        text3.setForeground(new java.awt.Color(235, 235, 250));
        text3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        text3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(text3);
        text3.setBounds(290, 230, 80, 20);

        icon3.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        icon3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/music.png"))); // NOI18N
        icon3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                icon3MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                icon3MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                icon3MouseEntered(evt);
            }
        });
        jPanel1.add(icon3);
        icon3.setBounds(290, 230, 50, 51);

        del4.setBackground(new java.awt.Color(235, 15, 15));
        del4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/x.png"))); // NOI18N
        del4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                del4MouseClicked(evt);
            }
        });
        jPanel1.add(del4);
        del4.setBounds(360, 230, 20, 20);

        text4.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        text4.setForeground(new java.awt.Color(235, 235, 250));
        text4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        text4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(text4);
        text4.setBounds(360, 230, 80, 20);

        icon4.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        icon4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/music.png"))); // NOI18N
        icon4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                icon4MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                icon4MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                icon4MouseEntered(evt);
            }
        });
        jPanel1.add(icon4);
        icon4.setBounds(360, 230, 50, 51);

        BG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/backgroundS.jpg"))); // NOI18N
        BG.setText("jLabel8");
        jPanel1.add(BG);
        BG.setBounds(-1, -8, 570, 330);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 560, 320);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        if (ch != 0 && on){
            ch--;
            switch (ch){
                case 0:
                    jLabel3.setText("87.7");
                    break;
                case 1:
                    jLabel3.setText("91.7");
                    break;
                case 2:
                    jLabel3.setText("97.6");
                    break;
                case 3:
                    jLabel3.setText("102.0");
                    break;
                case 4:
                    jLabel3.setText("106.2");
                    break;
                case 5:
                    jLabel3.setText("106.4");
                    break;
            }
        }
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
            if (ch != 5 && on){
            ch++;
            switch (ch){
                case 0:
                    jLabel3.setText("87.7");
                    break;
                case 1:
                    jLabel3.setText("91.7");
                    break;
                case 2:
                    jLabel3.setText("97.6");
                    break;
                case 3:
                    jLabel3.setText("102.0");
                    break;
                case 4:
                    jLabel3.setText("106.2");
                    break;
                case 5:
                    jLabel3.setText("106.4");
                    break;
            }
        }
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton8MouseClicked
        // TODO add your handling code here:
        if (on){
            on = false;
            jLabel3.setText("0FF");
        }
        else{
            on = true;
            switch (ch){
                case 0:
                    jLabel3.setText("87.7");
                    break;
                case 1:
                    jLabel3.setText("91.7");
                    break;
                case 2:
                    jLabel3.setText("97.6");
                    break;
                case 3:
                    jLabel3.setText("102.0");
                    break;
                case 4:
                    jLabel3.setText("106.2");
                    break;
                case 5:
                    jLabel3.setText("106.4");
                    break;
            }
        }
    }//GEN-LAST:event_jButton8MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
        if (on){
            if (!"".equals(text1.getText()) && !"".equals(text2.getText()) && !"".equals(text3.getText()) && "".equals(text4.getText())){
                text4.setText(jLabel3.getText());
                icon4.setVisible(true);
                //text4.setVisible(true);
                del4.setVisible(true);
                chan4 = ch;
            }
            if (!"".equals(text1.getText()) && !"".equals(text2.getText()) && "".equals(text3.getText())){
                text3.setText(jLabel3.getText());
                icon3.setVisible(true);
                //text3.setVisible(true);
                del3.setVisible(true);
                chan3 = ch;
            }
            if (!"".equals(text1.getText()) && "".equals(text2.getText())){
                text2.setText(jLabel3.getText());
                icon2.setVisible(true);
                //text2.setVisible(true);
                del2.setVisible(true);
                chan2 = ch;
            }
            if ("".equals(text1.getText())){
                text1.setText(jLabel3.getText());
                icon1.setVisible(true);
                //text1.setVisible(true);
                del1.setVisible(true);
                chan1 = ch;
            }
        }
    }//GEN-LAST:event_jButton3MouseClicked

    private void del1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_del1MouseClicked
        // TODO add your handling code here:
        if (!"".equals(text1.getText())){
            text1.setText("");
            icon1.setVisible(false);
            text1.setVisible(false);
            del1.setVisible(false);
        }
    }//GEN-LAST:event_del1MouseClicked

    private void del2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_del2MouseClicked
        // TODO add your handling code here:
        if (!"".equals(text2.getText())){
            text2.setText("");
            icon2.setVisible(false);
            text2.setVisible(false);
            del2.setVisible(false);
        }
    }//GEN-LAST:event_del2MouseClicked

    private void del3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_del3MouseClicked
        // TODO add your handling code here:
        if (!"".equals(text3.getText())){
            text3.setText("");
            icon3.setVisible(false);
            text3.setVisible(false);
            del3.setVisible(false);
        }
    }//GEN-LAST:event_del3MouseClicked

    private void del4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_del4MouseClicked
        // TODO add your handling code here:
        if (!"".equals(text4.getText())){
            text4.setText("");
            icon4.setVisible(false);
            text4.setVisible(false);
            del4.setVisible(false);
        }
    }//GEN-LAST:event_del4MouseClicked

    private void icon1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icon1MouseEntered
        // TODO add your handling code here:
        text1.setVisible(true);
    }//GEN-LAST:event_icon1MouseEntered

    private void icon1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icon1MouseExited
        // TODO add your handling code here:
        text1.setVisible(false);
    }//GEN-LAST:event_icon1MouseExited

    private void icon2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icon2MouseEntered
        // TODO add your handling code here:
        text2.setVisible(true);
    }//GEN-LAST:event_icon2MouseEntered

    private void icon2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icon2MouseExited
        // TODO add your handling code here:
        text2.setVisible(false);
    }//GEN-LAST:event_icon2MouseExited

    private void icon3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icon3MouseEntered
        // TODO add your handling code here:
        text3.setVisible(true);
    }//GEN-LAST:event_icon3MouseEntered

    private void icon3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icon3MouseExited
        // TODO add your handling code here:
        text3.setVisible(false);
    }//GEN-LAST:event_icon3MouseExited

    private void icon4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icon4MouseEntered
        // TODO add your handling code here:
        text4.setVisible(true);
    }//GEN-LAST:event_icon4MouseEntered

    private void icon4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icon4MouseExited
        // TODO add your handling code here:
        text4.setVisible(false);
    }//GEN-LAST:event_icon4MouseExited

    private void icon1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icon1MouseClicked
        // TODO add your handling code here:
        if (on){
            ch = chan1;
            switch (ch){
                case 0:
                    jLabel3.setText("87.7");
                    break;
                case 1:
                    jLabel3.setText("91.7");
                    break;
                case 2:
                    jLabel3.setText("97.6");
                    break;
                case 3:
                    jLabel3.setText("102.0");
                    break;
                case 4:
                    jLabel3.setText("106.2");
                    break;
                case 5:
                    jLabel3.setText("106.4");
                    break;
            }
        }
    }//GEN-LAST:event_icon1MouseClicked

    private void icon2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icon2MouseClicked
        // TODO add your handling code here:
        if (on){
            ch = chan2;
            switch (ch){
                case 0:
                    jLabel3.setText("87.7");
                    break;
                case 1:
                    jLabel3.setText("91.7");
                    break;
                case 2:
                    jLabel3.setText("97.6");
                    break;
                case 3:
                    jLabel3.setText("102.0");
                    break;
                case 4:
                    jLabel3.setText("106.2");
                    break;
                case 5:
                    jLabel3.setText("106.4");
                    break;
            }
        }
    }//GEN-LAST:event_icon2MouseClicked

    private void icon3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icon3MouseClicked
        // TODO add your handling code here:
        if (on){
            ch = chan3;
            switch (ch){
                case 0:
                    jLabel3.setText("87.7");
                    break;
                case 1:
                    jLabel3.setText("91.7");
                    break;
                case 2:
                    jLabel3.setText("97.6");
                    break;
                case 3:
                    jLabel3.setText("102.0");
                    break;
                case 4:
                    jLabel3.setText("106.2");
                    break;
                case 5:
                    jLabel3.setText("106.4");
                    break;
            }
        }
    }//GEN-LAST:event_icon3MouseClicked

    private void icon4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icon4MouseClicked
        // TODO add your handling code here:
        if (on){
            ch = chan4;
            switch (ch){
                case 0:
                    jLabel3.setText("87.7");
                    break;
                case 1:
                    jLabel3.setText("91.7");
                    break;
                case 2:
                    jLabel3.setText("97.6");
                    break;
                case 3:
                    jLabel3.setText("102.0");
                    break;
                case 4:
                    jLabel3.setText("106.2");
                    break;
                case 5:
                    jLabel3.setText("106.4");
                    break;
            }
        }
    }//GEN-LAST:event_icon4MouseClicked

    private void jButton9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton9MouseClicked
        // TODO add your handling code here:
        if (th == 4){
            th = 0;
        }
        else{
            th++;
        }
        switch (th){
            case 0:
                BG.setIcon(new ImageIcon(getClass().getResource("/img/backgroundS.jpg")));
                icon1.setIcon(new ImageIcon(getClass().getResource("/img/music.png")));
                icon2.setIcon(new ImageIcon(getClass().getResource("/img/music.png")));
                icon3.setIcon(new ImageIcon(getClass().getResource("/img/music.png")));
                icon4.setIcon(new ImageIcon(getClass().getResource("/img/music.png")));
                jPanel2.setBackground(new Color(175,175,250));
                jLabel3.setForeground(new Color(20,20,60));
                break;
            case 1:
                BG.setIcon(new ImageIcon(getClass().getResource("/img/background_autumnS.jpg")));
                icon1.setIcon(new ImageIcon(getClass().getResource("/img/leaf.png")));
                icon2.setIcon(new ImageIcon(getClass().getResource("/img/leaf.png")));
                icon3.setIcon(new ImageIcon(getClass().getResource("/img/leaf.png")));
                icon4.setIcon(new ImageIcon(getClass().getResource("/img/leaf.png")));
                jPanel2.setBackground(new Color(200,85,5));
                jLabel3.setForeground(new Color(85,200,5));
                break;
            case 2:
                BG.setIcon(new ImageIcon(getClass().getResource("/img/background_winterS.jpg")));
                icon1.setIcon(new ImageIcon(getClass().getResource("/img/penguin.png")));
                icon2.setIcon(new ImageIcon(getClass().getResource("/img/penguin.png")));
                icon3.setIcon(new ImageIcon(getClass().getResource("/img/penguin.png")));
                icon4.setIcon(new ImageIcon(getClass().getResource("/img/penguin.png")));
                jPanel2.setBackground(new Color(230,230,255));
                jLabel3.setForeground(new Color(20,20,60));
                break;
            case 3:
                BG.setIcon(new ImageIcon(getClass().getResource("/img/background_beachS.jpg")));
                icon1.setIcon(new ImageIcon(getClass().getResource("/img/seastar.png")));
                icon2.setIcon(new ImageIcon(getClass().getResource("/img/seastar.png")));
                icon3.setIcon(new ImageIcon(getClass().getResource("/img/seastar.png")));
                icon4.setIcon(new ImageIcon(getClass().getResource("/img/seastar.png")));
                jPanel2.setBackground(new Color(15,230,230));
                jLabel3.setForeground(new Color(110,110,10));
                break;
            case 4:
                BG.setIcon(new ImageIcon(getClass().getResource("/img/background_desertS.jpg")));
                icon1.setIcon(new ImageIcon(getClass().getResource("/img/sun.png")));
                icon2.setIcon(new ImageIcon(getClass().getResource("/img/sun.png")));
                icon3.setIcon(new ImageIcon(getClass().getResource("/img/sun.png")));
                icon4.setIcon(new ImageIcon(getClass().getResource("/img/sun.png")));
                jPanel2.setBackground(new Color(255,165,20));
                jLabel3.setForeground(new Color(140,20,20));
                break;
        }
    }//GEN-LAST:event_jButton9MouseClicked
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Radio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Radio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Radio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Radio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Radio().setVisible(true);
            }
        });
        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BG;
    private javax.swing.JButton del1;
    private javax.swing.JButton del2;
    private javax.swing.JButton del3;
    private javax.swing.JButton del4;
    private javax.swing.JLabel icon1;
    private javax.swing.JLabel icon2;
    private javax.swing.JLabel icon3;
    private javax.swing.JLabel icon4;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JLabel text1;
    private javax.swing.JLabel text2;
    private javax.swing.JLabel text3;
    private javax.swing.JLabel text4;
    // End of variables declaration//GEN-END:variables

}
